# Generated by Django 5.0.2 on 2024-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_biomovimenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='scientific_name',
            field=models.CharField(default='', max_length=100, verbose_name='Correct name'),
        ),
    ]
