# Generated by Django 5.0.2 on 2024-02-19 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_muscle_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='action',
            field=models.ManyToManyField(to='workout.biomovimenttype'),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='cover',
            field=models.FileField(blank=True, upload_to='images/muscles/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='scientific_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Correct name'),
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('muscle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout.muscle')),
                ('origins', models.ManyToManyField(related_name='muscle_origins', to='workout.muscle', verbose_name='Heads (origins)')),
            ],
            bases=('workout.muscle',),
        ),
    ]
