# Generated by Django 5.0.2 on 2024-02-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_muscle_action_alter_muscle_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscle',
            name='insertion',
        ),
        migrations.RemoveField(
            model_name='muscle',
            name='origin',
        ),
        migrations.AddField(
            model_name='muscle',
            name='insertion',
            field=models.ManyToManyField(related_name='bone_insertions', to='workout.bone'),
        ),
        migrations.AddField(
            model_name='muscle',
            name='origin',
            field=models.ManyToManyField(related_name='bone_origin', to='workout.bone'),
        ),
    ]
