# Generated by Django 5.0.2 on 2024-02-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_muscle_insertion_remove_muscle_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
