# Generated by Django 5.0.2 on 2024-02-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='origins',
            field=models.ManyToManyField(blank=True, related_name='muscle_origins', to='workout.muscle', verbose_name='Heads (origins)'),
        ),
    ]
