# Generated by Django 5.0.2 on 2024-02-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_bone_slug_joint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bone',
            name='is_spine_bone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
