# Generated by Django 5.0.2 on 2024-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_bone_is_spine_bone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomovimenttype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='joint',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movimenttype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='muscle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bone',
            name='is_skull_bone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
