# Generated by Django 5.0.2 on 2024-03-04 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_alter_biomovimenttype_options_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_barbell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_cable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_dumbell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='resistance_profile',
            field=models.CharField(blank=True, choices=[('Unk', 'Unknown'), ('Asc', 'Ascending'), ('Dow', 'Downward')], max_length=3, verbose_name='Resistance profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of sets'),
        ),
        migrations.AlterField(
            model_name='bone',
            name='cover',
            field=models.FileField(blank=True, upload_to='images/bones/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
