# Generated by Django 5.0.2 on 2024-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_exercise_is_barbell_exercise_is_cable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='steps',
            field=models.TextField(blank=True, verbose_name='Steps'),
        ),
    ]
