# Generated by Django 5.0.2 on 2024-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_exercise_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_machine',
            field=models.BooleanField(default=False),
        ),
    ]
