# Generated by Django 5.0.2 on 2024-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_exercise_is_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(related_name='MuscleGroup', to='workout.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(related_name='Muscle', to='workout.muscle'),
        ),
    ]
