# Generated by Django 5.0.2 on 2024-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_exercise_muscle_group_alter_exercise_muscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='related_exercises',
            field=models.ManyToManyField(to='workout.exercise'),
        ),
    ]
