# Generated by Django 5.0.2 on 2024-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0016_muscle_related_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='Muscle', to='workout.muscle'),
        ),
    ]
