# Generated by Django 5.0.2 on 2024-03-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0017_alter_exercise_muscles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetExerciseRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=1, verbose_name='Qty of Sets')),
                ('initial_margin_expected_reps', models.IntegerField(blank=True, verbose_name='Min. of reps:')),
                ('final_margin_expected_reps', models.IntegerField(blank=True, verbose_name='Max. of reps:')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Workout name')),
                ('set_exercise_relationships', models.ManyToManyField(to='workout.setexerciserelationship')),
            ],
        ),
    ]
