# Generated by Django 5.0.2 on 2024-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0020_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
