# Generated by Django 5.0.2 on 2024-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0023_alter_setexerciserelationship_final_margin_expected_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bone',
            name='attribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='attribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joint',
            name='attribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='muscle',
            name='attribution',
            field=models.TextField(blank=True),
        ),
    ]
